---

- name: Check if grub is present
  stat: path=/etc/default/grub
  register: hasgrub

## linux.yml: disable usb storage drivers - grub

## Enable IOMMU, requires VT-d - DMA attack coverage. partial? perf impact?
## ANSSI R11
## https://www.sstic.org/2010/presentation/Analyse_de_l_efficacite_du_service_fourni_par_une_IOMMU/
## https://www.cs.tau.ac.il/~mad/publications/asplos2016-iommu.pdf
## http://www.stewin.org/papers/dimvap15-stewin.pdf
- block:
    - name: Enable IOMMU in grub
      replace:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
        replace: 'GRUB_CMDLINE_LINUX="\1 iommu=force"'
        mode: '0644'
        backup: "{{ harden_backup | default(false) }}"
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        ) and hasgrub.stat.exists and harden_enable_iommu_force
